server:
  port: 8888

spring:
  application:
    name: stundenzettel
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: stundenzettel

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: stundenzettel